# Generated by Django 2.1 on 2018-09-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20180913_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='abstract',
            new_name='introduction',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='labels',
            new_name='label',
        ),
    ]
