# Generated by Django 2.1 on 2018-09-12 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0002_auto_20180909_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSubRoutine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_num', models.IntegerField()),
                ('icon', models.URLField()),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.URLField()),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('template', models.TextField()),
                ('default', models.TextField(blank=True, default='', null=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_steps', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='collected_steps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentJson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_json', models.TextField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.ImageField(blank=True, null=True, upload_to='report_graph')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_graphs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubRoutine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rt_type', models.CharField(choices=[('ST', 'Steps'), ('IN', 'Info'), ('RE', 'Result'), ('PI', 'Pictures'), ('QU', 'Quote'), ('TE', 'Text'), ('TA', 'Table')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SubRoutineJson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_json', models.TextField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubroutingComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_default_json', models.TextField()),
                ('order', models.IntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Component')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MainSubRoutine',
            fields=[
                ('basesubroutine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report.BaseSubRoutine')),
            ],
            bases=('report.basesubroutine',),
        ),
        migrations.CreateModel(
            name='ResultSubRoutine',
            fields=[
                ('basesubroutine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report.BaseSubRoutine')),
                ('Result', models.TextField()),
            ],
            bases=('report.basesubroutine',),
        ),
        migrations.AddField(
            model_name='report',
            name='subrouting_json',
            field=models.ManyToManyField(to='report.SubRoutineJson'),
        ),
        migrations.AddField(
            model_name='subroutingcomponent',
            name='sub_routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.MainSubRoutine'),
        ),
        migrations.AddField(
            model_name='subroutine',
            name='main_subuoutine',
            field=models.ManyToManyField(to='report.MainSubRoutine'),
        ),
        migrations.AddField(
            model_name='subroutine',
            name='result_subroutine',
            field=models.ManyToManyField(to='report.ResultSubRoutine'),
        ),
        migrations.AddField(
            model_name='mainsubroutine',
            name='data',
            field=models.ManyToManyField(through='report.SubroutingComponent', to='report.Component'),
        ),
    ]
