# Generated by Django 2.1 on 2018-09-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20180915_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='envs',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
