# Generated by Django 2.1 on 2018-09-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_report_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='envs',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='label',
            field=models.ManyToManyField(null=True, related_name='reports_related', to='report.Label'),
        ),
    ]
